### ISSUE TITLE
Submitting a new contact needs to provide positive feedback contact was saved

### ISSUE THREAD

**Issue by gregelin** [GovReady/GovReady-Drupal-Agent#49] opened 2017-04-06 18:19 UTC
Entering a new contact in Drupal dashboard just flashes screen. It does not reply with a "contact saved" submission. It is not clear if contact is actually saved.

**Comment by jlyon** [comment] 2017-04-12 15:40
Dupe of #47

**Closed as completed** 2017-04-12 15:40 UTC
Labels: bug
